use serde::{Deserialize, Serialize};
use sqlx::FromRow;

#[derive(Serialize, Deserialize, FromRow, Clone)]
pub struct Players {
    pub id: i64,
    pub name: String,
    pub team_id: Option<i64>,
    pub runs_scored: i32,
    pub user_id: i64,
    pub wickets_taken: i32,
    pub matches_played: Option<i32>,
    pub batting_average: f64,
    pub bowling_average: f64,
    pub role: String,
    pub dob: i32,
    pub strike_rate: f64,
    pub over_bowled: f64,
    pub economy_rate: f64,
    pub five_wicket_hauls: i32,
    pub centuries: i32,
    pub half_centuries: i32,
    pub player_of_the_match_awards: i32,
    pub player_of_the_series_awards: i32,
    pub highest_score: i32,
    pub best_bowling_figures: String,
    pub is_active: bool,
    pub debut_date: Option<String>,
    pub last_match_date: Option<String>,
    pub profile_picture_url: Option<String>,
    pub bio: Option<String>,
    pub ball_faced: i32,
    pub fours: i32,
    pub sixes: i32,
    pub three_wicket_hauls: i32,
    pub catches: i32,
    pub stumpings: i32,
}